version: '2'
services:
  app:
    build: .
    image: rails_app
    volumes:
      - .:/app
      - /app/log # persist logs
    depends_on:
      - db

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - app
    depends_on:
      - app

  db:
    restart: always
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"